export const MY_PAGE_SCREEN = 'MY_PAGE_SCREEN';

// navigator
export const BOTTOM_TAB_NAVIGATOR = 'BOTTOM_TAB_NAVIGATOR';
export const COMMON_STACK_NAVIGATOR = 'COMMON_STACK_NAVIGATOR';
export const HOME_STACK_NAVIGATOR = 'HOME_STACK_NAVIGATOR';
export const DATE_STACK_NAVIGATOR = 'DATE_STACK_NAVIGATOR';
export const MESSAGE_STACK_NAVIGATOR = 'MESSAGE_STACK_NAVIGATOR';
export const MY_PAGE_STACK_NAVIGATOR = 'MY_PAGE_STACK_NAVIGATOR';

// Sign
export const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN';
export const REGISTER_FIRST_SCREEN = 'REGISTER_FIRST_SCREEN';

// MANAGER
export const MANAGER_HOME_SCREEN = 'MANAGER_HOME_SCREEN';
export const MANAGER_HOME_STACK_NAVIGATOR = 'MANAGER_HOME_STACK_NAVIGATOR';
export const MANAGER_MESSAGE_STACK_NAVIGATOR =
  'MANAGER_MESSAGE_STACK_NAVIGATOR';
export const MANAGER_PROFILE_STACK_NAVIGATOR =
  'MANAGER_PROFILE_STACK_NAVIGATOR';

// MANAGER HOME
export const MANAGER_CREATE_ROOM_SCREEN = 'MANAGER_CREATE_ROOM_SCREEN';

// MANAGER HOUSE
export const MANAGER_CREATE_HOUSE_SCREEN = 'MANAGER_CREATE_HOUSE_SCREEN';

// PROFILE
export const MANAGER_PROFILE_SCREEN = 'MANAGER_PROFILE_SCREEN';

export default {
  MY_PAGE_SCREEN,
  BOTTOM_TAB_NAVIGATOR,
  COMMON_STACK_NAVIGATOR,
  HOME_STACK_NAVIGATOR,
  DATE_STACK_NAVIGATOR,
  MESSAGE_STACK_NAVIGATOR,
  MY_PAGE_STACK_NAVIGATOR,
  SIGN_IN_SCREEN,
  MANAGER_HOME_SCREEN,
  REGISTER_FIRST_SCREEN,
  MANAGER_HOME_STACK_NAVIGATOR,
  MANAGER_MESSAGE_STACK_NAVIGATOR,
  MANAGER_PROFILE_STACK_NAVIGATOR,
  MANAGER_PROFILE_SCREEN,
  MANAGER_CREATE_ROOM_SCREEN,
  MANAGER_CREATE_HOUSE_SCREEN,
};
